services:
  e2e:
    build: .
    image: bootcamp/ext-e2e:latest
    environment:
      - CI=true
      - PLAYWRIGHT_HTML_REPORT=/app/playwright-report
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: npm run test:e2e
    shm_size: 2gb  # evita falhas do Chromium por falta de shared memory