name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Instalar dependências
        run: npm ci
      
      - name: Instalar Playwright Chromium
        run: npx playwright install --with-deps chromium
      
      - name: Build extensão
        run: npm run build
      
      - name: Executar testes E2E
        run: npm run test:e2e
        continue-on-error: true
      
      - name: Publicar relatório do Playwright
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      
      - name: Publicar pacote da extensão
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extension-zip
          path: dist/extension.zip
          retention-days: 30
      
      - name: Verificar se testes passaram
        run: npm run test:e2e

  docker-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build imagem Docker
        run: docker compose build
      
      - name: Executar testes no container
        run: docker compose run --rm e2e
      
      - name: Publicar relatório do Docker
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-docker
          path: playwright-report/
          retention-days: 30